### ISSUE TITLE
Words are highlighted incorrect after regular text in Safari

### ISSUE THREAD

**Issue by Nick-filipchuk** [sudodoki/react-textarea-highlight#2]
Type any words and after that type col, where or column in Safari
http://recordit.co/Du3jiTH7Ba

**Comment by sudodoki** [comment]
Note: Highlight Language Example

**Comment by sudodoki** [comment]
Supposedly, fixed via 574154879a6ebfe8bdc346ce6fc639d8a87de58b

**Comment by sudodoki** [comment]
@Nick-filipchuk let me know if this persist 😉

**Comment by Nick-filipchuk** [comment]
it is

![image](https://cloud.githubusercontent.com/assets/14974338/22736374/8035b418-ee06-11e6-9138-b58a984c776d.png)
